export * from './Landing/landing'
export * from './LoginRegister/login'
export * from './LoginRegister/register'
export * from './Menu/menu'
export * from './Surveys/surveySelection'
export * from './Candidacies/candidacies'